# Generated by Django 4.2.5 on 2023-09-21 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='accounts.usertype'),
        ),
    ]
