<<<<<<< HEAD
# Generated by Django 4.2.5 on 2023-10-19 21:22
=======
# Generated by Django 4.2.5 on 2023-09-24 03:06
>>>>>>> main

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.usertype'),
        ),
    ]
