# Generated by Django 4.2.5 on 2023-10-21 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_email'),
        ('accounts', '0005_usertypelist'),
    ]

    operations = [
    ]
