# Generated by Django 4.2.5 on 2023-10-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_0005_alter_customuser_email_0005_usertypelist'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usertypelist',
            constraint=models.UniqueConstraint(fields=('user_type', 'user'), name='userTypeList_unique_entry'),
        ),
    ]
